/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ClientInput = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'notes' : IDL.Text,
  'phone' : IDL.Text,
});
export const ClientId = IDL.Text;
export const Time = IDL.Int;
export const Client = IDL.Record({
  'id' : ClientId,
  'name' : IDL.Text,
  'createdAt' : Time,
  'email' : IDL.Text,
  'notes' : IDL.Text,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  'addClient' : IDL.Func([ClientInput], [], []),
  'deleteClient' : IDL.Func([ClientId], [], []),
  'editClient' : IDL.Func([ClientId, ClientInput], [], []),
  'getAllClients' : IDL.Func([], [IDL.Vec(Client)], ['query']),
  'getClient' : IDL.Func([ClientId], [Client], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ClientInput = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'notes' : IDL.Text,
    'phone' : IDL.Text,
  });
  const ClientId = IDL.Text;
  const Time = IDL.Int;
  const Client = IDL.Record({
    'id' : ClientId,
    'name' : IDL.Text,
    'createdAt' : Time,
    'email' : IDL.Text,
    'notes' : IDL.Text,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    'addClient' : IDL.Func([ClientInput], [], []),
    'deleteClient' : IDL.Func([ClientId], [], []),
    'editClient' : IDL.Func([ClientId, ClientInput], [], []),
    'getAllClients' : IDL.Func([], [IDL.Vec(Client)], ['query']),
    'getClient' : IDL.Func([ClientId], [Client], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };