/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Client {
  'id' : ClientId,
  'name' : string,
  'createdAt' : Time,
  'email' : string,
  'notes' : string,
  'phone' : string,
}
export type ClientId = string;
export interface ClientInput {
  'name' : string,
  'email' : string,
  'notes' : string,
  'phone' : string,
}
export type Time = bigint;
export interface Reply {
  'id' : string,
  'clientId' : ClientId,
  'channel' : string,
  'message' : string,
  'createdAt' : Time,
}
export interface _SERVICE {
  'addClient' : ActorMethod<[ClientInput], undefined>,
  'deleteClient' : ActorMethod<[ClientId], undefined>,
  'editClient' : ActorMethod<[ClientId, ClientInput], undefined>,
  'getAllClients' : ActorMethod<[], Array<Client>>,
  'getClient' : ActorMethod<[ClientId], Client>,
  'addReply' : ActorMethod<[ClientId, string, string], undefined>,
  'getReplies' : ActorMethod<[ClientId], Array<Reply>>,
  'deleteReply' : ActorMethod<[string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];
